"""add user_events table

Revision ID: 52a34a9b9134
Revises: d66b0fedceba
Create Date: 2026-08-02 01:09:54.152641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52a34a9b9134'
down_revision: Union[str, Sequence[str], None] = 'd66b0fedceba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=False),
    sa.Column('client_event_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_event_id')
    )
    op.create_index(op.f('ix_user_events_created_at'), 'user_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_events_product_id'), 'user_events', ['product_id'], unique=False)
    op.create_index('ix_user_events_session_created', 'user_events', ['session_id', 'created_at'], unique=False)
    op.create_index('ix_user_events_user_created', 'user_events', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_user_events_user_id'), 'user_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_events_user_id'), table_name='user_events')
    op.drop_index('ix_user_events_user_created', table_name='user_events')
    op.drop_index('ix_user_events_session_created', table_name='user_events')
    op.drop_index(op.f('ix_user_events_product_id'), table_name='user_events')
    op.drop_index(op.f('ix_user_events_created_at'), table_name='user_events')
    op.drop_table('user_events')
    # ### end Alembic commands ###
