"""add recommendation_snapshots table

Revision ID: 66a6b0cf91b9
Revises: 52a34a9b9134
Create Date: 2026-08-02 18:50:04.261755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66a6b0cf91b9'
down_revision: Union[str, Sequence[str], None] = '52a34a9b9134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('strategy', sa.String(length=20), nullable=False),
    sa.Column('retrieval_refined', sa.Boolean(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('narration_text', sa.Text(), nullable=True),
    sa.Column('narration_grounded', sa.Boolean(), nullable=False),
    sa.Column('narration_fallback_reason', sa.String(length=40), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_snapshots_user_id'), 'recommendation_snapshots', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_snapshots_user_id'), table_name='recommendation_snapshots')
    op.drop_table('recommendation_snapshots')
    # ### end Alembic commands ###
